services:
  
  nginx:
    image: golenski/fibonacci-nginx:1.0
    container_name: fibonacci-nginx
    ports: 
      - "8180:80"
    depends_on: 
      - task-manager

  front-app:
    image: golenski/fibonacci-front:1.1
    container_name: fibonacci-front
    depends_on: 
      - task-manager
    
  task-manager:
    image: golenski/fibonacci-task-manager:1.3.0
    container_name: fibonacci-task-manager
    env_file: 
      - env/task-manager.env
      - env/postgres.env
      - env/broker.env
    depends_on: 
      - postgres
      - artemis
      - db-init

  fibworker:
    image: golenski/fibonacci-worker:1.3.0
    container_name: fibonacci-fibworker
    env_file: 
      - env/fib-worker.env
      - env/broker.env
    depends_on:
      - artemis

  postgres:
    image: postgres:16.4
    container_name: fibonacci-postgres
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
    env_file: 
        - env/postgres.env

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: fibonacci-pgadmin
    env_file:
        - env/pgadmin.env
    ports:
        - "8181:80"

  artemis:
    image: apache/activemq-artemis:2.37.0
    container_name: fibonacci-artemis
    ports:
      - "8182:8161"

  db-init:
    image: golenski/db-init:1.0.0
    container_name: fibonacci-db-init
    env_file:
      - env/postgres.env
    environment:
      - POSTGRES_DB_NAME=task_manager
      - POSTGRES_DB_HOST=fibonacci-postgres
    depends_on:
      - postgres