version: "3.4"
services: 
  
  nginx:
    image: golenski/fibonacci-nginx:1.0
    container_name: fibonacci-nginx
    build: 
      dockerfile: Dockerfile
      context: ./nginx/
    ports: 
      - "8180:80"
    depends_on: 
      - front-app
      - task-manager

  front-app:
    image: golenski/fibonacci-front:1.1
    container_name: fibonacci-front
    build: 
      dockerfile: Dockerfile
      context: ../front-app/
    
  task-manager:
    image: golenski/fibonacci-task-manager:1.1
    container_name: fibonacci-task-manager
    build:
      dockerfile: Dockerfile
      context: ../task-manager/
    env_file: 
      - env/task-manager.env
      - env/postgres.env
      - env/broker.env
    depends_on: 
      - postgres
      - activemq

  fibworker:
    image: golenski/fibonacci-worker:1.1
    # container_name: fibonacci-fibworker
    build:
      dockerfile: Dockerfile
      context: ../fib-worker/
    env_file: 
      - env/fib-worker.env
      - env/broker.env
    
  postgres:
    image: postgres:10.6
    container_name: fibonacci-postgres
    volumes:
      - ../storage/postgresql/data:/var/lib/postgresql/data
    env_file: 
        - env/postgres.env

  pgadmin:
    image: dpage/pgadmin4:4.25
    container_name: fibonacci-pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=postgres
        - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
        - "8181:80"

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: fibonacci-activemq
    ports:
        - "8182:8161"