version: "3.4"
services: 
  
  front-app:
    image: gol/docker-demo-front:1.0
    container_name: docker-demo-front
    build: 
      dockerfile: Dockerfile
      context: ../front-app/
    ports: 
      - "8180:80"
    depends_on: 
      - task-manager
    
  task-manager:
    image: gol/task-manager:1.0
    container_name: docker-demo-task-manager
    build:
      dockerfile: Dockerfile
      context: ../task-manager/
    env_file: 
      - env/task-manager.env
      - env/postgres.env
      - env/broker.env
    depends_on: 
      - postgres
      - activemq

  fibworker:
    image: gol/fibworker:1.0
    # container_name: docker-demo-fibworker
    build:
      dockerfile: Dockerfile
      context: ../fib-worker/
    env_file: 
      - env/fib-worker.env
      - env/broker.env
    
  postgres:
    image: postgres:10.6
    container_name: docker-demo-postgres
    env_file: 
        - env/postgres.env

  pgadmin:
    image: dpage/pgadmin4:4.25
    container_name: docker-demo-pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=postgres
        - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
        - "8181:80"

  activemq:
    image: rmohr/activemq:latest
    container_name: docker-demo-activemq
    ports:
        - "8182:8161"