services:
  
  nginx:
    image: golenski/fibonacci-nginx:1.0
    container_name: fibonacci-nginx
    ports: 
      - "8180:80"
    depends_on: 
      - task-manager

  front-app:
    image: golenski/fibonacci-front:2.0.0
    container_name: fibonacci-front
    depends_on: 
      - task-manager
    
  task-manager:
    image: golenski/fibonacci-task-manager:2.0.0
    container_name: fibonacci-task-manager
    env_file: 
      - env/task-manager.env
      - env/postgres.env
      - env/broker.env
    depends_on: 
      - postgres
      - artemis
      - db-init
    deploy:
      resources:
        limits:
          memory: 600M

  msg-relay:
    image: golenski/fibonacci-msg-relay:1.0.0
    container_name: fibonacci-msg-relay
    env_file:
      - env/msg-relay.env
      - env/postgres.env
      - env/broker.env
    depends_on:
      - postgres
      - artemis
      - task-manager
    deploy:
      resources:
        limits:
          memory: 300M

  fibworker-1:
    image: golenski/fibonacci-worker:2.0.0
    container_name: fibonacci-fibworker-1
    env_file: 
      - env/fib-worker.env
      - env/broker.env
      - env/redis.env
    depends_on:
      - artemis
      - redis
    deploy:
      resources:
        limits:
          memory: 300M

  fibworker-2:
    image: golenski/fibonacci-worker:2.0.0
    container_name: fibonacci-fibworker-2
    env_file:
      - env/fib-worker.env
      - env/broker.env
      - env/redis.env
    depends_on:
      - artemis
      - redis
    deploy:
      resources:
        limits:
          memory: 300M

  postgres:
    image: postgres:16.4
    container_name: fibonacci-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: 
        - env/postgres.env
    deploy:
      resources:
        limits:
          memory: 2G

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: fibonacci-pgadmin
    env_file:
        - env/pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
        - "8181:80"
    deploy:
      resources:
        limits:
          memory: 2G

  artemis:
    image: apache/activemq-artemis:2.37.0
    container_name: fibonacci-artemis
    volumes:
      - artemis-data:/var/lib/artemis-instance
    ports:
      - "8182:8161"
    deploy:
      resources:
        limits:
          memory: 2G

  redis:
    image: redis:7.4.1
    container_name: fibonacci-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 2G

  db-init:
    image: golenski/db-init:1.0.0
    container_name: fibonacci-db-init
    env_file:
      - env/postgres.env
    environment:
      - POSTGRES_DB_NAME=task_manager
      - POSTGRES_DB_HOST=fibonacci-postgres
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
  artemis-data:
  redis-data: