services:

  postgres:
    image: postgres:16.4
    container_name: fibonacci-postgres
    env_file:
      - env/postgres.env
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: fibonacci-pgadmin
    env_file:
      - env/pgadmin.env
    ports:
      - "5480:80"

  artemis:
    image: apache/activemq-artemis:2.37.0
    container_name: fibonacci-artemis
    ports:
      - "61616:61616"
      - "8161:8161"