version: "3.4"
services:

  postgres:
    image: postgres:10.6
    container_name: fibonacci-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ../storage/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:4.25
    container_name: fibonacci-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5480:80"

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: fibonacci-activemqs
    ports:
      - "61616:61616"
      - "8161:8161"