services:

  postgres:
    image: postgres:16.4
    container_name: fibonacci-postgres
    env_file:
      - env/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: fibonacci-pgadmin
    env_file:
      - env/pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5480:80"

  artemis:
    image: apache/activemq-artemis:2.37.0
    container_name: fibonacci-artemis
    volumes:
      - artemis-data:/var/lib/artemis-instance
    ports:
      - "61616:61616"
      - "8161:8161"

  redis:
    image: redis:7.4.1
    container_name: fibonacci-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  db-init:
    image: golenski/db-init:1.0.0
    container_name: fibonacci-db-init
    env_file:
      - env/postgres.env
    environment:
      - POSTGRES_DB_NAME=task_manager
      - POSTGRES_DB_HOST=fibonacci-postgres
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
  artemis-data:
  redis-data:


